class Grat < Formula
  desc "Run approved local development tasks safely"
  homepage "https://github.com/phranck/grat"
  url "https://github.com/phranck/grat/archive/refs/tags/v1.8.0.tar.gz"
  sha256 "27428330cf19d7acdf4efd6e52cb246a0d735173868e02578ce9c061f67a38cc"
  license "MIT"

  bottle do
    root_url "https://github.com/phranck/grat/releases/download/v1.8.0"
    sha256 cellar:       :any_skip_relocation,
           arm64_tahoe:  "2d8cb7bcac95c0407a1af356af345ba8e5d669ffe13e03950f8ab551d7e45499",
           arm64_linux:  "27bb9b4bc3af3054f6b296d25d6e2b0fe170d25495a121ee4faa46b8dd85a9d9",
           tahoe:        "05b90ff0ab68ff8cba455bfd5f6f0d7cf32f98d9d2a3e45709b7ec1e35fb753a",
           x86_64_linux: "9f9b0fb3af7ca41d2fb72f0a53832e83799ea0d4a14b33751abac8e4cb3843ab"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/phranck/grat/internal/version.buildVersion=v#{version}"), "./cmd/grat"
    # Both pages are generated by the binary that was just built, so they can
    # only ever describe that binary.
    (buildpath/"grat.1").write Utils.safe_popen_read(bin/"grat", "manual")
    (buildpath/"grat.config.7").write Utils.safe_popen_read(bin/"grat", "manual", "grat.config")
    man1.install "grat.1"
    man7.install "grat.config.7"
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/grat version")
    assert_match "GRAT 1", (man1/"grat.1").read
    assert_match "GRAT.CONFIG 7", (man7/"grat.config.7").read
  end
end
