class Grat < Formula
  desc "Run approved local development tasks safely"
  homepage "https://github.com/phranck/grat"
  url "https://github.com/phranck/grat/archive/refs/tags/v1.6.0.tar.gz"
  sha256 "b7bc6faf79c6f4c5f10c099d58672d73f399d18c308f2294eba191212ff39289"
  license "MIT"

  bottle do
    root_url "https://github.com/phranck/grat/releases/download/v1.6.0"
    sha256 cellar:       :any_skip_relocation,
           arm64_tahoe:  "861467c2bf4b474d495e350aa290eb56abdf34690ab29bcfc952f890cf515005",
           arm64_linux:  "bc479d482cb578336548d37c348b193a4d404cceedd11456d5835e74e37c67fb",
           tahoe:        "1f6529a89444cb00ba20bf9e9c20780df9e726a8a7c8efc539bb927a798d757a",
           x86_64_linux: "26e1368402d75f405a85fecf992d3e1a5cb3e154bd0d7908056c93ad11d797b6"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/phranck/grat/internal/version.buildVersion=v#{version}"), "./cmd/grat"
    # Both pages are generated by the binary that was just built, so they can
    # only ever describe that binary.
    (buildpath/"grat.1").write Utils.safe_popen_read(bin/"grat", "manual")
    (buildpath/"grat.config.7").write Utils.safe_popen_read(bin/"grat", "manual", "grat.config")
    man1.install "grat.1"
    man7.install "grat.config.7"
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/grat version")
    assert_match "GRAT 1", (man1/"grat.1").read
    assert_match "GRAT.CONFIG 7", (man7/"grat.config.7").read
  end
end
