class Grat < Formula
  desc "Run approved local development tasks safely"
  homepage "https://github.com/phranck/grat"
  url "https://github.com/phranck/grat/archive/refs/tags/v2.1.0.tar.gz"
  sha256 "fcfc81e482449985fba270dcd9e2f0f5e3707b75ad5221164a8610073ab0c94d"
  license "MIT"

  bottle do
    root_url "https://github.com/phranck/grat/releases/download/v2.1.0"
    sha256 cellar:       :any_skip_relocation,
           arm64_tahoe:  "6bbf4e337649fea567ade9953eb8f355cefa9deaa3e5d2ff9a4640660c750f6e",
           arm64_linux:  "91caa0537c8dd675fe979334f88cc78220c1ab95031f65fa8a0e56e5204cbdf0",
           tahoe:        "b1dce3d4394103c1818c8cff21a1bed5f51cf4d481e16c8390f9c536bc34d209",
           x86_64_linux: "d227e21722fcca0649625a48304f873f0a3d754e6173a57d86dda05dccb7732d"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/phranck/grat/internal/version.buildVersion=v#{version}"), "./cmd/grat"
    # Both pages are generated by the binary that was just built, so they can
    # only ever describe that binary.
    (buildpath/"grat.1").write Utils.safe_popen_read(bin/"grat", "manual")
    (buildpath/"grat.config.7").write Utils.safe_popen_read(bin/"grat", "manual", "grat.config")
    man1.install "grat.1"
    man7.install "grat.config.7"
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/grat version")
    assert_match "GRAT 1", (man1/"grat.1").read
    assert_match "GRAT.CONFIG 7", (man7/"grat.config.7").read
  end
end
